### ISSUE TITLE
Declaration Java Issue

### ISSUE THREAD

**Issue by abhis021** [HarshSharma001/Music-Player#1]
Import error suspected in Declaration.java file.

imported 
"import jaco.mp3.player.MP3Player;"

lets correct it because of this it won't run on my system.

Or let me know of the Jaco library

**Comment by HarshSharma001** [comment]
Here's the jar file download link, it's not a built-in library : http://jacomp3player.sourceforge.net/

Hopefully this may resolve the issue

**Comment by abhis021** [comment]
I don't understand how to use the jar file to install the library...,

I tried but failed.

**Comment by abhis021** [comment]
Suggestion to make an exe or jar file of the total program so that it can be run standalone.

**Comment by HarshSharma001** [comment]
I'll make such changes sooner, but for the time being, can you mention in which ide you're executing java files. So that I can provide subsequent resources from where you can learn how to add Jar files to your project.

**Comment by abhis021** [comment]
Its VSCODE.

**Comment by HarshSharma001** [comment]
Now you'll find no errors in dependencies, and you can easily run the application and enjoy it. The stabilised version is being released.
